repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.5.7"
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: generate-test-markdown
        name: Generate test markdown from schema examples
        entry: scripts/generate-tests.sh
        language: script
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*\\.md$"
      - id: end-of-file-fixer
      - id: check-added-large-files
