name: Linting

on: [push, pull_request]

jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
      - name: Black formatting
        run: poetry run black --diff .
      - name: Ruff check
        run: poetry run ruff --check --output-format=github .
